### ISSUE TITLE
Cannot run sol-contract example

### ISSUE THREAD

**Issue by 5elfle5** [pyth-network/pyth-sdk-rs#83]
1. cd examples/sol-contract
2. cargo build
error
`no method named `get_current_price` found for struct `PriceFeed` in the current scope`
`examples/sol-contract/src/processor.rs:87:33`
`let result1 = feed1.get_current_price().ok_or(ProgramError::Custom(3))?;`

If I rollback to commit 'An example contract for solana (#72)' I can go one step further:

1. cd examples/sol-contract
2. cargo build
3. cd scripts
4. sh build.sh

error
`error: failed to select a version for the requirement time = "^0.3"`
`candidate versions found which didn't match: 0.3.15, 0.3.14, 0.3.13,`

**Comment by yhzhang0128** [comment]
Thanks for reporting the issue and sorry for the confusion. We recently updated the Pyth SDK interface causing this issue. I am working on it and I expect to have it fixed in the next few days.

**Comment by jayantk** [comment]
PR for reference https://github.com/pyth-network/pyth-sdk-rs/pull/84

**Comment by 5elfle5** [comment]
@yhzhang0128 tried your branch 'adapt-api', still getting error 'failed to select a version for the requirement `time = "^0.3"`' on 'sh build.sh'

**Comment by ali-bahjati** [comment]
Hi @5elfle5, can you please [update your solana cli tools](https://docs.solana.com/cli/install-solana-cli-tools) to the latest version? This solves the issue you are facing now. (#85 describes more)
